config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources crea el crud directamente resources :tasks
  # resources :tasks

  # Read
  get 'tasks', to: 'tasks#index', as: :tasks
  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new', as: :newtask
  get 'tasks/:id/edit', to: 'tasks#edit', as: :editask
  get 'tasks/:id', to: 'tasks#show', as: :task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params).save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title, "introdusca Titulo" %>
  <%= f.text_field :title %>

  <%= f.label :details, "introdusca descripcion" %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Nuestras tares</h1>
<% @tasks.each do |task| %>
<p><input type="checkbox" <%= "checked" if task.completed %> disabled="disabled"><%= link_to task.title, task_path(task)%></p>
<% end %>
<%= link_to "+ Crear nueva tarea", newtask_path %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title, "introdusca Titulo" %>
  <%= f.text_field :title %>

  <%= f.label :details, "introdusca descripcion" %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

<%# <form action="/tasks" method"post">
  <label for="title">Entrar titulo</label>
  <input type="text" name="task[title]" placeholder="TITULO">
  <label for="details">Entrar Detalles</label>
  <input type="text" name="task[details]" placeholder="detalles">
  <input type="submit" >
</form>
 %>

app/views/tasks/show.html.erb
<h1> <%= @task.title %> </h1>
<p> <%= @task.details %> </p>
<p> completada : <%= @task.completed ? "Si" : "No" %> </p>
<%= link_to "editar", editask_path(@task) %> ||
<%= link_to "borrar", task_path(@task), method: :delete %> ||
<%= link_to "Volver al las tareas", tasks_path %>